### ISSUE TITLE
How to particpate ?

### ISSUE THREAD

**Issue by MaximumProgrammer** [rust-lang/rustc_codegen_gcc#48]
Is it possbile to participate in anyway on this project like an open source project ?

Kind regards

**Comment by antoyo** [comment]
Yes!
If you have any question, don't hesitate to ask me.

**Comment by ggsvr** [comment]
What resources do you recommend to start contributing? I'm really looking forward to using this backend to compile for AVR targets,  and would like to help where possible, but I have absolutely no idea how to get started. Thanks.

**Comment by MaximumProgrammer** [comment]
Hello i am new to Rust but i have experience with other programming languages like C/C++ and Python, my background is mainly High Performance Computing, Compilier Optimizations and Programming on CPUs/GPUs.

Kind regards.

**Comment by antoyo** [comment]
So, currently, a useful thing to do would be to run the tests (see instructions in the readme) and pick a failing one, debug it and fixing the issue in the backend.
The code generation is mostly done in [this impl](https://github.com/antoyo/rustc_codegen_gcc/blob/ff755d3e1f732b91e325eb52cf8b0093086e7e28/src/builder.rs#L455), so getting familiar with it would be a good first step.

Here's how I debug an issue:

 * I copy the failing test in [an external project](https://github.com/antoyo/rustc_codegen_gcc/blob/master/gcc-test-backend/src/main.rs) and run `../cargo.sh build` from the `gcc-test-backend` directory.
 * I'll either look at the generated GIMPLE, but adding an environment variable in the previous command, as in `CG_GCCJIT_DUMP_GIMPLE=1 ../cargo.sh build`.
 * Or, I'll debug the generated program using gdb.

I can give you more details once you get more familiar with those steps and I can answer your questions, then.

Hope this helps.

(If you have any suggestion on how I could help you, please suggest them: it's a complicated project and I'm not sure how best to help you.)

**Comment by ggsvr** [comment]
I think it's best for me to learn more about compilers and gcc's intermediate representation before trying to contribute to this project. Once I'm not completely lost, I'll try to get back to it.

**Comment by ggsvr** [comment]
Ok, so I have a few questions regarding the project.

1: Where exactly does cg_gcc take place? Is it right after monomorphization?

2: Since libgccjit.so requires a different .so for every target, does the project needs to link to every libgccjit available at compile time, or is there a way to make this library resolution at runtime? For example, if I wanted to add a new target with libgccjit, would I need to recompile the project to link with the new library?

3: Since libgccjit is ABI stable, would it be as simple as compiling libgccjit for different targets, without any extra work from this project side?

Please tell if any question is unclear. English is not my first language, and I'm not familiar with some of these terms.

**Comment by antoyo** [comment]
For #1, it is after monomorphization.

For #2, how is this different than this project?

For #3, it's not decided yet how we would do this, but there are ways like `LD_LIBRARY_PATH` to load another `libgccjit.so` at run-time.

For #4, Mostly, since we could use `LD_LIBRARY_PATH`. However, there might some weird architectures that don't support some integer types or have different ABI, so there might be some work needed either in this project or in rustc.

**Comment by MaximumProgrammer** [comment]
It would be also cool to have a list for other people especially for things which are open and already at work.

Kind regards

**Comment by antoyo** [comment]
@MaximumProgrammer You mean having GitHub issues for things to do and things being worked on?

**Comment by MaximumProgrammer** [comment]
> @MaximumProgrammer You mean having GitHub issues for things to do and things being worked on?

Yes exactly so other people can choose and participate maybe not each topic but great topics which are open like compiler optimization or finding bugs

**Comment by antoyo** [comment]
Good. I'll start creating issues and tag some as [good first issue](https://github.com/antoyo/rustc_codegen_gcc/labels/good%20first%20issue).

**Comment by antoyo** [comment]
I'll close this as I explain in my [blog posts](https://blog.antoyo.xyz/rustc_codegen_gcc-progress-report-7#how_to_contribute) how to contribute.
